// ---------------------------------------------------------------------------------------------------------------------
//  <copyright>
//    This file is part of FinnHub MCP Server and is licensed under the MIT License.
//    See the LICENSE file in the project root for full license information.
//  </copyright>
// ---------------------------------------------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace FinnHub.MCP.Server.Application.Search.Features.SearchSymbol;

/// <summary>
/// Represents the response from a symbol search operation: the matching <see cref="StockSymbol"/>
/// collection plus correlation and timing metadata. Serialised to JSON for MCP responses.
/// </summary>
/// <remarks>
/// Self-contained response following the canonical <c>{Feature}Response</c> shape (no shared base
/// class). <see cref="TotalCount"/> and <see cref="HasResults"/> are derived from <see cref="Symbols"/>.
/// </remarks>
[ExcludeFromCodeCoverage]
public sealed class SearchSymbolResponse
{
    /// <summary>
    /// Gets the original search query string that produced this response.
    /// </summary>
    [JsonPropertyName("query")]
    public string Query { get; init; } = string.Empty;

    /// <summary>
    /// Gets the opaque correlation token (typically a truncated GUID) generated by the query
    /// builder. Pairs with <see cref="Query"/> so logs and clients can trace a response back to
    /// the request that produced it.
    /// </summary>
    [JsonPropertyName("query_id")]
    public string QueryId { get; init; } = string.Empty;

    /// <summary>
    /// Gets the elapsed time taken to execute the search.
    /// </summary>
    [JsonPropertyName("search_duration")]
    public TimeSpan SearchDuration { get; init; }

    /// <summary>
    /// Gets the UTC timestamp when the search was executed.
    /// </summary>
    [JsonPropertyName("search_timestamp")]
    public DateTime SearchTimestamp { get; init; }

    /// <summary>
    /// Gets the data source the results originated from (e.g., "finnhub-api").
    /// </summary>
    [JsonPropertyName("source")]
    public string Source { get; init; } = string.Empty;

    /// <summary>
    /// Gets the matching stock symbols, ordered by relevance. Empty when nothing matched.
    /// </summary>
    [JsonPropertyName("symbols")]
    public IReadOnlyList<StockSymbol> Symbols { get; init; } = [];

    /// <summary>
    /// Gets the number of symbols in <see cref="Symbols"/>.
    /// </summary>
    [JsonPropertyName("total_count")]
    public int TotalCount => this.Symbols.Count;

    /// <summary>
    /// Gets a value indicating whether the search returned any symbols.
    /// </summary>
    [JsonPropertyName("has_results")]
    public bool HasResults => this.TotalCount > 0;
}
