name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            artifact_name: finnhub-mcp-linux-x64
          - os: windows-latest
            runtime: win-x64
            artifact_name: finnhub-mcp-win-x64.exe
          - os: macos-latest
            runtime: osx-x64
            artifact_name: finnhub-mcp-osx-x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish src/FinnHub.MCP.Server/FinnHub.MCP.Server.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./publish

      - name: Create artifact
        shell: bash
        run: |
          cd ./publish
          if [ "${{ matrix.runtime }}" == "win-x64" ]; then
            # Find the .exe file and rename it
            find . -name "*.exe" -type f -exec mv {} ${{ matrix.artifact_name }} \;
          else
            # Find the main executable (should be the largest file without extension)
            EXECUTABLE=$(find . -type f -executable ! -name "*.dll" ! -name "*.so" ! -name "*.dylib" ! -name "*.json" ! -name "*.pdb" | head -1)
            if [ -n "$EXECUTABLE" ]; then
              mv "$EXECUTABLE" ${{ matrix.artifact_name }}
            else
              # Fallback: look for files without extensions
              EXECUTABLE=$(find . -type f ! -name "*.*" | head -1)
              mv "$EXECUTABLE" ${{ matrix.artifact_name }}
            fi
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./publish/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Download artifacts
        uses: actions/download-artifact@v4

      - name: 🔄 Generate Conventional Changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: 📝 Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.changes != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: 📦 ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false

      - name: 📤 Upload Linux Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-linux-x64
          asset_name: finnhub-mcp-linux-x64
          asset_content_type: application/octet-stream

      - name: 📤 Upload Windows Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-win-x64.exe
          asset_name: finnhub-mcp-win-x64.exe
          asset_content_type: application/octet-stream

      - name: 📤 Upload macOS Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-osx-x64
          asset_name: finnhub-mcp-osx-x64
          asset_content_type: application/octet-stream
