name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            artifact_name: finnhub-mcp-linux-x64
          - os: windows-latest
            runtime: win-x64
            artifact_name: finnhub-mcp-win-x64.exe
          - os: macos-latest
            runtime: osx-x64
            artifact_name: finnhub-mcp-osx-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 📦 Restore
        run: dotnet restore

      - name: 🏗️ Build & Publish
        run: dotnet publish src/FinnHub.MCP.Server/FinnHub.MCP.Server.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: 🧼 Prepare artifact
        shell: bash
        run: |
          cd ./publish
          if [ "${{ matrix.runtime }}" == "win-x64" ]; then
            EXEC=$(find . -name "*.exe" -type f | head -1)
            mv "$EXEC" ${{ matrix.artifact_name }}
          else
            EXEC=$(find . -type f -perm -111 ! -name "*.dll" ! -name "*.so" ! -name "*.dylib" ! -name "*.json" ! -name "*.pdb" | head -1)
            if [ -n "$EXEC" ]; then
              mv "$EXEC" ${{ matrix.artifact_name }}
            else
              EXEC=$(find . -type f ! -name "*.*" | head -1)
              mv "$EXEC" ${{ matrix.artifact_name }}
            fi
          fi
          mkdir -p ../artifacts
          mv ${{ matrix.artifact_name }} ../artifacts/

      - name: ⬆️ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./artifacts/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 📝 Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: 🚀 Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.changes != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: 📦 ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false

      - name: 📤 Upload Linux Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-linux-x64/finnhub-mcp-linux-x64
          asset_name: finnhub-mcp-linux-x64
          asset_content_type: application/octet-stream

      - name: 📤 Upload Windows Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-win-x64.exe/finnhub-mcp-win-x64.exe
          asset_name: finnhub-mcp-win-x64.exe
          asset_content_type: application/octet-stream

      - name: 📤 Upload macOS Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/finnhub-mcp-osx-x64/finnhub-mcp-osx-x64
          asset_name: finnhub-mcp-osx-x64
          asset_content_type: application/octet-stream
